"""Add all missing item names from item_names.json to all .po files"""
import json
import polib
import os

os.chdir(os.path.dirname(os.path.abspath(__file__)) + '/..')

# Load item names
item_names = json.load(open('assets/items/map/item_names.json', 'r', encoding='utf-8'))
names_set = set(item_names)

LANGS = ['en_US', 'zh_CN', 'zh_TW', 'es_ES', 'ja_JP', 'ko_KR']

# English translations for all 126 missing item names
EN_TRANSLATIONS = {
    "Delta型机器人": "Delta-type Robot",
    "“碾骨之拳”罗丹": '"Bone-Crushing Fist" Rodan',
    "中红柱状菌": "Medium Red Column Fungus",
    "中黯石": "Medium Dimstone",
    "仓储节点": "Storage Node",
    "仿生翅天使": "Bionic Wing Angel",
    "会客室": "Lounge",
    "传送台": "Teleport Pad",
    "供电终端": "Power Terminal",
    "充能球刺兽": "Charged Spike Beast",
    "净水节点": "Water Purification Node",
    "分层入口": "Layered Entrance",
    "刚角天使": "Hardhorn Angel",
    "割云翁": "Cloud Reaper",
    "劫云客": "Cloud Raider",
    "协议传送点": "Protocol Teleport",
    "协议奇点": "Protocol Singularity",
    "协议核心": "Protocol Core",
    "协议采录桩": "Protocol Recording Stake",
    "原生钳兽": "Native Pincer Beast",
    "受蚀玉化叶": "Eroded Jade Leaf",
    "大角天使": "Large Horn Angel",
    "大角天使α": "Large Horn Angel α",
    "展示区": "Display Area",
    "岩天使叶": "Rock Angel Leaf",
    "巨山犼兽": "Mountain Howler Beast",
    "干员联络台": "Operator Contact Station",
    "开天将": "Sky Opener",
    "怒目彪兽": "Glaring Beast",
    "总控中枢": "Central Control Hub",
    "战术训练": "Tactical Training",
    "摧山将": "Mountain Crusher",
    "斧甲兽": "Axe Shell Beast",
    "断云叟": "Cloud Cutter",
    "星门菌": "Star Gate Fungus",
    "映火荞花": "Fire Buckwheat Flower",
    "晶化多齿叶": "Crystallized Multi-Serrated Leaf",
    "晶锥天使": "Crystal Cone Angel",
    "晶锥天使δ": "Crystal Cone Angel δ",
    "柑实": "Citrus Fruit",
    "棱镜天使": "Prism Angel",
    "次级核心": "Secondary Core",
    "武陵石": "Wuling Stone",
    "残暴原生钳兽": "Ferocious Native Pincer Beast",
    "水灯虫": "Water Lantern Bug",
    "浊流天使": "Turbid Stream Angel",
    "浊流天使δ": "Turbid Stream Angel δ",
    "源矿矿点": "Originium Ore Deposit",
    "演武平台": "Training Platform",
    "潜地虬兽": "Burrowing Dragon Beast",
    "潮行天使": "Tide Walker Angel",
    "潮行天使δ": "Tide Walker Angel δ",
    "火雾源石虫": "Fire Mist Originium Slug",
    "灰芦麦": "Grey Reed Wheat",
    "灼壳虫": "Scorched Shell Bug",
    "焚雾源石虫": "Burning Mist Originium Slug",
    "燎石": "Blazing Stone",
    "物资调度终端": "Material Dispatch Terminal",
    "环境监测终端": "Environment Monitor Terminal",
    "球刺兽": "Spike Ball Beast",
    "琼叶参": "Jade Leaf Ginseng",
    "百眼彪兽": "Hundred-Eyed Beast",
    "砂叶": "Sand Leaf",
    "碾骨伏击射手": "Bone-Crushing Ambusher",
    "碾骨先锋": "Bone-Crushing Vanguard",
    "碾骨劫掠者": "Bone-Crushing Raider",
    "碾骨撕裂牙兽": "Bone-Crushing Rending Fang Beast",
    "碾骨清道夫": "Bone-Crushing Scavenger",
    "碾骨渗透者": "Bone-Crushing Infiltrator",
    "碾骨焰术师": "Bone-Crushing Pyromancer",
    "碾骨行刑人": "Bone-Crushing Executioner",
    "穿林箭": "Forest Piercer",
    "精锐伏击射手": "Elite Ambusher",
    "精锐劫掠者": "Elite Raider",
    "精锐撕裂牙兽": "Elite Rending Fang Beast",
    "精锐行刑人": "Elite Executioner",
    "紫晶矿矿点": "Amethyst Ore Deposit",
    "纯晶多齿叶": "Pure Crystal Multi-Serrated Leaf",
    "维修灵感点": "Repair Inspiration Point",
    "肖像天使": "Portrait Angel",
    "能量淤积点": "Energy Accumulation Point",
    "至晶多齿叶": "Supreme Crystal Multi-Serrated Leaf",
    "芽针": "Sprout Needle",
    "苦叶椒": "Bitter Leaf Pepper",
    "荆刺芽针": "Thorn Sprout Needle",
    "荞花": "Buckwheat Flower",
    "莫惜命": "Spare No Life",
    "莫留财": "Spare No Wealth",
    "萤壳虫": "Firefly Shell Bug",
    "蓝铁矿矿点": "Blue Iron Ore Deposit",
    "蓬茸锦草": "Fluffy Brocade Grass",
    "蚀像寻遗": "Eroded Image Relic",
    "血菌": "Blood Fungus",
    "行迹高塔": "Trace Tower",
    "表象": "Appearance",
    "袭击预警终端": "Raid Warning Terminal",
    "装备模板箱": "Equipment Template Box",
    "见闻辑录": "Knowledge Archive",
    "访客终端": "Visitor Terminal",
    "资源回收站": "Resource Recycling Station",
    "赤铜矿": "Red Copper Ore",
    "轻红柱状菌": "Light Red Column Fungus",
    "轻黯石": "Light Dimstone",
    "过堂风": "Draft Wind",
    "酮化灌木": "Ketone Shrub",
    "酸液源石虫": "Acid Originium Slug",
    "酸液源石虫·α": "Acid Originium Slug · α",
    "重刺天使": "Heavy Thorn Angel",
    "重刺天使α": "Heavy Thorn Angel α",
    "重红柱状菌": "Heavy Red Column Fungus",
    "重黯石": "Heavy Dimstone",
    "金石稻": "Gold Stone Rice",
    "钉刺天使": "Spike Thorn Angel",
    "钉刺天使α": "Spike Thorn Angel α",
    "锁闭储藏箱": "Locked Storage Box",
    "锦草": "Brocade Grass",
    "雾火斧甲兽": "Mistfire Axe Shell Beast",
    "雾火爪牙": "Mistfire Minion",
    "雾火牙兽": "Mistfire Fang Beast",
    "音像存档": "Audio Archive",
    "高阶培养I": "Advanced Cultivation I",
    "高阶培养II": "Advanced Cultivation II",
    "高阶培养III": "Advanced Cultivation III",
    "高阶培养IV": "Advanced Cultivation IV",
    "高阶培养V": "Advanced Cultivation V",
    "黯银柑实": "Dark Silver Citrus",
}

# Traditional Chinese conversion map (simplified -> traditional)
SIMPLIFIED_TO_TRADITIONAL = {
    "Delta型机器人": "Delta型機器人",
    "“碾骨之拳”罗丹": "「碾骨之拳」羅丹",
    "中红柱状菌": "中紅柱狀菌",
    "中黯石": "中黯石",
    "仓储节点": "倉儲節點",
    "仿生翅天使": "仿生翅天使",
    "会客室": "會客室",
    "传送台": "傳送台",
    "供电终端": "供電終端",
    "充能球刺兽": "充能球刺獸",
    "净水节点": "淨水節點",
    "分层入口": "分層入口",
    "刚角天使": "剛角天使",
    "割云翁": "割雲翁",
    "劫云客": "劫雲客",
    "协议传送点": "協議傳送點",
    "协议奇点": "協議奇點",
    "协议核心": "協議核心",
    "协议采录桩": "協議採錄樁",
    "原生钳兽": "原生鉗獸",
    "受蚀玉化叶": "受蝕玉化葉",
    "大角天使": "大角天使",
    "大角天使α": "大角天使α",
    "展示区": "展示區",
    "岩天使叶": "岩天使葉",
    "巨山犼兽": "巨山犼獸",
    "干员联络台": "幹員聯絡台",
    "开天将": "開天將",
    "怒目彪兽": "怒目彪獸",
    "总控中枢": "總控中樞",
    "战术训练": "戰術訓練",
    "摧山将": "摧山將",
    "斧甲兽": "斧甲獸",
    "断云叟": "斷雲叟",
    "星门菌": "星門菌",
    "映火荞花": "映火蕎花",
    "晶化多齿叶": "晶化多齒葉",
    "晶锥天使": "晶錐天使",
    "晶锥天使δ": "晶錐天使δ",
    "柑实": "柑實",
    "棱镜天使": "稜鏡天使",
    "次级核心": "次級核心",
    "武陵石": "武陵石",
    "残暴原生钳兽": "殘暴原生鉗獸",
    "水灯虫": "水燈蟲",
    "浊流天使": "濁流天使",
    "浊流天使δ": "濁流天使δ",
    "源矿矿点": "源礦礦點",
    "演武平台": "演武平台",
    "潜地虬兽": "潛地虯獸",
    "潮行天使": "潮行天使",
    "潮行天使δ": "潮行天使δ",
    "火雾源石虫": "火霧源石蟲",
    "灰芦麦": "灰蘆麥",
    "灼壳虫": "灼殼蟲",
    "焚雾源石虫": "焚霧源石蟲",
    "燎石": "燎石",
    "物资调度终端": "物資調度終端",
    "环境监测终端": "環境監測終端",
    "球刺兽": "球刺獸",
    "琼叶参": "瓊葉參",
    "百眼彪兽": "百眼彪獸",
    "砂叶": "砂葉",
    "碾骨伏击射手": "碾骨伏擊射手",
    "碾骨先锋": "碾骨先鋒",
    "碾骨劫掠者": "碾骨劫掠者",
    "碾骨撕裂牙兽": "碾骨撕裂牙獸",
    "碾骨清道夫": "碾骨清道夫",
    "碾骨渗透者": "碾骨滲透者",
    "碾骨焰术师": "碾骨焰術師",
    "碾骨行刑人": "碾骨行刑人",
    "穿林箭": "穿林箭",
    "精锐伏击射手": "精銳伏擊射手",
    "精锐劫掠者": "精銳劫掠者",
    "精锐撕裂牙兽": "精銳撕裂牙獸",
    "精锐行刑人": "精銳行刑人",
    "紫晶矿矿点": "紫晶礦礦點",
    "纯晶多齿叶": "純晶多齒葉",
    "维修灵感点": "維修靈感點",
    "肖像天使": "肖像天使",
    "能量淤积点": "能量淤積點",
    "至晶多齿叶": "至晶多齒葉",
    "芽针": "芽針",
    "苦叶椒": "苦葉椒",
    "荆刺芽针": "荊刺芽針",
    "荞花": "蕎花",
    "莫惜命": "莫惜命",
    "莫留财": "莫留財",
    "萤壳虫": "螢殼蟲",
    "蓝铁矿矿点": "藍鐵礦礦點",
    "蓬茸锦草": "蓬茸錦草",
    "蚀像寻遗": "蝕像尋遺",
    "血菌": "血菌",
    "行迹高塔": "行跡高塔",
    "表象": "表象",
    "袭击预警终端": "襲擊預警終端",
    "装备模板箱": "裝備模板箱",
    "见闻辑录": "見聞輯錄",
    "访客终端": "訪客終端",
    "资源回收站": "資源回收站",
    "赤铜矿": "赤銅礦",
    "轻红柱状菌": "輕紅柱狀菌",
    "轻黯石": "輕黯石",
    "过堂风": "過堂風",
    "酮化灌木": "酮化灌木",
    "酸液源石虫": "酸液源石蟲",
    "酸液源石虫·α": "酸液源石蟲·α",
    "重刺天使": "重刺天使",
    "重刺天使α": "重刺天使α",
    "重红柱状菌": "重紅柱狀菌",
    "重黯石": "重黯石",
    "金石稻": "金石稻",
    "钉刺天使": "釘刺天使",
    "钉刺天使α": "釘刺天使α",
    "锁闭储藏箱": "鎖閉儲藏箱",
    "锦草": "錦草",
    "雾火斧甲兽": "霧火斧甲獸",
    "雾火爪牙": "霧火爪牙",
    "雾火牙兽": "霧火牙獸",
    "音像存档": "音像存檔",
    "高阶培养I": "高階培養I",
    "高阶培养II": "高階培養II",
    "高阶培养III": "高階培養III",
    "高阶培养IV": "高階培養IV",
    "高阶培养V": "高階培養V",
    "黯银柑实": "黯銀柑實",
}

# Japanese translations (using English or katakana-based game terminology)
JA_TRANSLATIONS = {
    "Delta型机器人": "デルタ型ロボット",
    "“碾骨之拳”罗丹": "「骨砕きの拳」ローダン",
    "中红柱状菌": "中型紅柱菌",
    "中黯石": "中型暗色石",
    "仓储节点": "倉庫ノード",
    "仿生翅天使": "生体翅天使",
    "会客室": "応接室",
    "传送台": "転送台",
    "供电终端": "給電端末",
    "充能球刺兽": "充能球刺獣",
    "净水节点": "浄水ノード",
    "分层入口": "層状入口",
    "刚角天使": "剛角天使",
    "割云翁": "雲切りの翁",
    "劫云客": "雲刧の客",
    "协议传送点": "プロトコル転送点",
    "协议奇点": "プロトコル特異点",
    "协议核心": "プロトコルコア",
    "协议采录桩": "プロトコル採録杭",
    "原生钳兽": "原生鋏獣",
    "受蚀玉化叶": "侵食されし玉化葉",
    "大角天使": "大角天使",
    "大角天使α": "大角天使α",
    "展示区": "展示エリア",
    "岩天使叶": "岩天使葉",
    "巨山犼兽": "巨山吼獣",
    "干员联络台": "オペレーター連絡台",
    "开天将": "開天将",
    "怒目彪兽": "怒目彪獣",
    "总控中枢": "総制御中枢",
    "战术训练": "戦術訓練",
    "摧山将": "摧山将",
    "斧甲兽": "斧甲獣",
    "断云叟": "雲断ちの翁",
    "星门菌": "星門菌",
    "映火荞花": "映火蕎花",
    "晶化多齿叶": "晶化多歯葉",
    "晶锥天使": "晶錐天使",
    "晶锥天使δ": "晶錐天使δ",
    "柑实": "柑橘実",
    "棱镜天使": "プリズム天使",
    "次级核心": "次级核心",
    "武陵石": "武陵石",
    "残暴原生钳兽": "残暴原生鋏獣",
    "水灯虫": "水灯虫",
    "浊流天使": "濁流天使",
    "浊流天使δ": "濁流天使δ",
    "源矿矿点": "源鉱採掘場",
    "演武平台": "演武台",
    "潜地虬兽": "潜地虯獣",
    "潮行天使": "潮行天使",
    "潮行天使δ": "潮行天使δ",
    "火雾源石虫": "火霧源石蟲",
    "灰芦麦": "灰芦麦",
    "灼壳虫": "灼殼蟲",
    "焚雾源石虫": "焚霧源石蟲",
    "燎石": "燎石",
    "物资调度终端": "物資調度端末",
    "环境监测终端": "環境監測端末",
    "球刺兽": "球刺獣",
    "琼叶参": "瓊葉参",
    "百眼彪兽": "百眼彪獣",
    "砂叶": "砂葉",
    "碾骨伏击射手": "骨砕き伏撃射手",
    "碾骨先锋": "骨砕き先锋",
    "碾骨劫掠者": "骨砕き略奪者",
    "碾骨撕裂牙兽": "骨砕き裂牙獣",
    "碾骨清道夫": "骨砕き掃討者",
    "碾骨渗透者": "骨砕き浸透者",
    "碾骨焰术师": "骨砕き焔術師",
    "碾骨行刑人": "骨砕き行刑人",
    "穿林箭": "林穿ちの矢",
    "精锐伏击射手": "精鋭伏撃射手",
    "精锐劫掠者": "精鋭略奪者",
    "精锐撕裂牙兽": "精鋭裂牙獣",
    "精锐行刑人": "精鋭行刑人",
    "紫晶矿矿点": "紫晶鉱採掘場",
    "纯晶多齿叶": "純晶多歯葉",
    "维修灵感点": "修理インスピレーション",
    "肖像天使": "肖像天使",
    "能量淤积点": "エネルギー堆積点",
    "至晶多齿叶": "至晶多歯葉",
    "芽针": "芽針",
    "苦叶椒": "苦葉椒",
    "荆刺芽针": "荊刺芽針",
    "荞花": "蕎花",
    "莫惜命": "命を惜しまず",
    "莫留财": "財を残さず",
    "萤壳虫": "蛍殻虫",
    "蓝铁矿矿点": "藍鉄鉱採掘場",
    "蓬茸锦草": "蓬茸錦草",
    "蚀像寻遗": "蝕像遺跡",
    "血菌": "血菌",
    "行迹高塔": "行跡の塔",
    "表象": "表層",
    "袭击预警终端": "襲撃予警端末",
    "装备模板箱": "装備テンプレート箱",
    "见闻辑录": "見聞録",
    "访客终端": "来訪者端末",
    "资源回收站": "資源回収所",
    "赤铜矿": "赤銅鉱",
    "轻红柱状菌": "軽紅柱菌",
    "轻黯石": "軽暗色石",
    "过堂风": "通り風",
    "酮化灌木": "酮化低木",
    "酸液源石虫": "酸液源石蟲",
    "酸液源石虫·α": "酸液源石蟲·α",
    "重刺天使": "重刺天使",
    "重刺天使α": "重刺天使α",
    "重红柱状菌": "重紅柱菌",
    "重黯石": "重暗色石",
    "金石稻": "金石稲",
    "钉刺天使": "釘刺天使",
    "钉刺天使α": "釘刺天使α",
    "锁闭储藏箱": "施錠収納箱",
    "锦草": "錦草",
    "雾火斧甲兽": "霧火斧甲獣",
    "雾火爪牙": "霧火爪牙",
    "雾火牙兽": "霧火牙獣",
    "音像存档": "音像記録",
    "高阶培养I": "高階培養I",
    "高阶培养II": "高階培養II",
    "高阶培养III": "高階培養III",
    "高阶培养IV": "高階培養IV",
    "高阶培养V": "高階培養V",
    "黯银柑实": "黯銀柑橘実",
}

# Korean translations
KO_TRANSLATIONS = {
    "Delta型机器人": "델타형 로봇",
    "“碾骨之拳”罗丹": '"뼈를 부수는 주먹" 로단',
    "中红柱状菌": "중형 붉은 기둥 균",
    "中黯石": "중형 암석",
    "仓储节点": "창고 노드",
    "仿生翅天使": "생체 날개 천사",
    "会客室": "응접실",
    "传送台": "전송대",
    "供电终端": "전원 공급 단말",
    "充能球刺兽": "충전 구체 가시수",
    "净水节点": "정수 노드",
    "分层入口": "층형 입구",
    "刚角天使": "강각 천사",
    "割云翁": "구름 베는 노인",
    "劫云客": "구름 약탈자",
    "协议传送点": "프로토콜 전송 지점",
    "协议奇点": "프로토콜 특이점",
    "协议核心": "프로토콜 코어",
    "协议采录桩": "프로토콜 채록 말뚝",
    "原生钳兽": "원생 집게수",
    "受蚀玉化叶": "침식된 옥화 잎",
    "大角天使": "대각 천사",
    "大角天使α": "대각 천사 α",
    "展示区": "전시 구역",
    "岩天使叶": "암천사 잎",
    "巨山犼兽": "거산 후수",
    "干员联络台": "오퍼레이터 연락대",
    "开天将": "개천장",
    "怒目彪兽": "노목표수",
    "总控中枢": "총괄 제어 중추",
    "战术训练": "전술 훈련",
    "摧山将": "최산장",
    "斧甲兽": "도끼갑수",
    "断云叟": "구름 끊는 노인",
    "星门菌": "성문 균",
    "映火荞花": "불꽃 메밀꽃",
    "晶化多齿叶": "결정화 다치엽",
    "晶锥天使": "수정 원뿔 천사",
    "晶锥天使δ": "수정 원뿔 천사 δ",
    "柑实": "감귤 열매",
    "棱镜天使": "프리즘 천사",
    "次级核心": "차급 코어",
    "武陵石": "무릉석",
    "残暴原生钳兽": "잔폭 원생 집게수",
    "水灯虫": "수등충",
    "浊流天使": "탁류 천사",
    "浊流天使δ": "탁류 천사 δ",
    "源矿矿点": "원광 채굴 지점",
    "演武平台": "연무 플랫폼",
    "潜地虬兽": "잠지 규수",
    "潮行天使": "조행 천사",
    "潮行天使δ": "조행 천사 δ",
    "火雾源石虫": "화무 원석충",
    "灰芦麦": "회로맥",
    "灼壳虫": "작각충",
    "焚雾源石虫": "분무 원석충",
    "燎石": "요석",
    "物资调度终端": "물자 조달 단말",
    "环境监测终端": "환경 감시 단말",
    "球刺兽": "구자수",
    "琼叶参": "경엽삼",
    "百眼彪兽": "백안표수",
    "砂叶": "사엽",
    "碾骨伏击射手": "골분쇄 복격 사수",
    "碾骨先锋": "골분쇄 선봉",
    "碾骨劫掠者": "골분쇄 약탈자",
    "碾骨撕裂牙兽": "골분쇄 열아수",
    "碾骨清道夫": "골분쇄 청소부",
    "碾骨渗透者": "골분쇄 침투자",
    "碾骨焰术师": "골분쇄 염술사",
    "碾骨行刑人": "골분쇄 형집행인",
    "穿林箭": "관림전",
    "精锐伏击射手": "정예 복격 사수",
    "精锐劫掠者": "정예 약탈자",
    "精锐撕裂牙兽": "정예 열아수",
    "精锐行刑人": "정예 형집행인",
    "紫晶矿矿点": "자정광 채굴 지점",
    "纯晶多齿叶": "순정 다치엽",
    "维修灵感点": "수리 영감 포인트",
    "肖像天使": "초상 천사",
    "能量淤积点": "에너지 퇴적 지점",
    "至晶多齿叶": "지정 다치엽",
    "芽针": "아침",
    "苦叶椒": "고엽초",
    "荆刺芽针": "형자아침",
    "荞花": "메밀꽃",
    "莫惜命": "목석명",
    "莫留财": "막유재",
    "萤壳虫": "형각충",
    "蓝铁矿矿点": "남철광 채굴 지점",
    "蓬茸锦草": "방용금초",
    "蚀像寻遗": "식상심유",
    "血菌": "혈균",
    "行迹高塔": "행적 고탑",
    "表象": "표상",
    "袭击预警终端": "습격 예경 단말",
    "装备模板箱": "장비 템플릿 상자",
    "见闻辑录": "견문 집록",
    "访客终端": "방객 단말",
    "资源回收站": "자원 회수소",
    "赤铜矿": "적동광",
    "轻红柱状菌": "경홍주상균",
    "轻黯石": "경암석",
    "过堂风": "과당풍",
    "酮化灌木": "동화 관목",
    "酸液源石虫": "산액 원석충",
    "酸液源石虫·α": "산액 원석충 · α",
    "重刺天使": "중자천사",
    "重刺天使α": "중자천사 α",
    "重红柱状菌": "중홍주상균",
    "重黯石": "중암석",
    "金石稻": "금석도",
    "钉刺天使": "정자천사",
    "钉刺天使α": "정자천사 α",
    "锁闭储藏箱": "잠금 저장함",
    "锦草": "금초",
    "雾火斧甲兽": "무화부갑수",
    "雾火爪牙": "무화조아",
    "雾火牙兽": "무화아수",
    "音像存档": "음상 기록",
    "高阶培养I": "고급 배양 I",
    "高阶培养II": "고급 배양 II",
    "高阶培养III": "고급 배양 III",
    "高阶培养IV": "고급 배양 IV",
    "高阶培养V": "고급 배양 V",
    "黯银柑实": "암은감실",
}

# Spanish translations
ES_TRANSLATIONS = {
    "Delta型机器人": "Robot Tipo Delta",
    "“碾骨之拳”罗丹": '"Puño Triturador" Rodan',
    "中红柱状菌": "Hongo Columna Rojo Medio",
    "中黯石": "Piedra Oscura Media",
    "仓储节点": "Nodo de Almacenamiento",
    "仿生翅天使": "Ángel de Alas Biónicas",
    "会客室": "Sala de Estar",
    "传送台": "Plataforma de Teletransporte",
    "供电终端": "Terminal de Energía",
    "充能球刺兽": "Bestia Espina Cargada",
    "净水节点": "Nodo de Purificación",
    "分层入口": "Entrada de Capas",
    "刚角天使": "Ángel de Cuerno Duro",
    "割云翁": "Segador de Nubes",
    "劫云客": "Asaltante de Nubes",
    "协议传送点": "Teletransporte de Protocolo",
    "协议奇点": "Singularidad de Protocolo",
    "协议核心": "Núcleo de Protocolo",
    "协议采录桩": "Estaca de Grabación de Protocolo",
    "原生钳兽": "Bestia Pinza Nativa",
    "受蚀玉化叶": "Hoja de Jade Erosionada",
    "大角天使": "Ángel de Cuerno Grande",
    "大角天使α": "Ángel de Cuerno Grande α",
    "展示区": "Área de Exhibición",
    "岩天使叶": "Hoja de Ángel de Roca",
    "巨山犼兽": "Bestia Aulladora de Montaña",
    "干员联络台": "Estación de Contacto de Operadores",
    "开天将": "Abrecielos",
    "怒目彪兽": "Bestia Mirada Feroz",
    "总控中枢": "Centro de Control Central",
    "战术训练": "Entrenamiento Táctico",
    "摧山将": "Rompe Montañas",
    "斧甲兽": "Bestia Hacha de Caparazón",
    "断云叟": "Cortanubes",
    "星门菌": "Hongo Puerta Estelar",
    "映火荞花": "Flor de Alforfón de Fuego",
    "晶化多齿叶": "Hoja Multidentada Cristalizada",
    "晶锥天使": "Ángel de Cono de Cristal",
    "晶锥天使δ": "Ángel de Cono de Cristal δ",
    "柑实": "Fruto Cítrico",
    "棱镜天使": "Ángel Prisma",
    "次级核心": "Núcleo Secundario",
    "武陵石": "Piedra Wuling",
    "残暴原生钳兽": "Bestia Pinza Nativa Feroc",
    "水灯虫": "Insecto Linterna de Agua",
    "浊流天使": "Ángel de Corriente Turbia",
    "浊流天使δ": "Ángel de Corriente Turbia δ",
    "源矿矿点": "Depósito de Mineral de Origen",
    "演武平台": "Plataforma de Entrenamiento",
    "潜地虬兽": "Bestia Dragón Excavadora",
    "潮行天使": "Ángel Caminante de Mareas",
    "潮行天使δ": "Ángel Caminante de Mareas δ",
    "火雾源石虫": "Babosa de Origen Niebla de Fuego",
    "灰芦麦": "Trigo de Caña Gris",
    "灼壳虫": "Insecto de Caparazón Quemado",
    "焚雾源石虫": "Babosa de Origen Niebla Ardiente",
    "燎石": "Piedra Ardiente",
    "物资调度终端": "Terminal de Envío de Materiales",
    "环境监测终端": "Terminal de Monitoreo Ambiental",
    "球刺兽": "Bestia Espina Esférica",
    "琼叶参": "Ginseng de Hoja de Jade",
    "百眼彪兽": "Bestia de Cien Ojos",
    "砂叶": "Hoja de Arena",
    "碾骨伏击射手": "Francotirador Emboscador Triturador",
    "碾骨先锋": "Vanguardia Trituradora",
    "碾骨劫掠者": "Asaltante Triturador",
    "碾骨撕裂牙兽": "Bestia Colmillo Desgarrador Trituradora",
    "碾骨清道夫": "Carroñero Triturador",
    "碾骨渗透者": "Infiltrador Triturador",
    "碾骨焰术师": "Piromante Triturador",
    "碾骨行刑人": "Verdugo Triturador",
    "穿林箭": "Flecha Perforabosques",
    "精锐伏击射手": "Francotirador Emboscador Élite",
    "精锐劫掠者": "Asaltante Élite",
    "精锐撕裂牙兽": "Bestia Colmillo Desgarrador Élite",
    "精锐行刑人": "Verdugo Élite",
    "紫晶矿矿点": "Depósito de Mineral Amatista",
    "纯晶多齿叶": "Hoja Multidentada de Cristal Puro",
    "维修灵感点": "Punto de Inspiración de Reparación",
    "肖像天使": "Ángel Retrato",
    "能量淤积点": "Punto de Acumulación de Energía",
    "至晶多齿叶": "Hoja Multidentada de Cristal Supremo",
    "芽针": "Aguja Brote",
    "苦叶椒": "Pimienta de Hoja Amarga",
    "荆刺芽针": "Aguja Brote Espinosa",
    "荞花": "Flor de Alforfón",
    "莫惜命": "Sin Reserva Vital",
    "莫留财": "Sin Reserva de Riqueza",
    "萤壳虫": "Insecto de Caparazón de Luciérnaga",
    "蓝铁矿矿点": "Depósito de Mineral de Hierro Azul",
    "蓬茸锦草": "Hierba Brocado Esponjosa",
    "蚀像寻遗": "Reliquia de Imagen Erosionada",
    "血菌": "Hongo de Sangre",
    "行迹高塔": "Torre de Rastros",
    "表象": "Apariencia",
    "袭击预警终端": "Terminal de Alerta de Incursión",
    "装备模板箱": "Caja de Plantilla de Equipo",
    "见闻辑录": "Archivo de Conocimiento",
    "访客终端": "Terminal de Visitante",
    "资源回收站": "Estación de Reciclaje de Recursos",
    "赤铜矿": "Mineral de Cobre Rojo",
    "轻红柱状菌": "Hongo Columna Rojo Ligero",
    "轻黯石": "Piedra Oscura Ligera",
    "过堂风": "Viento de Paso",
    "酮化灌木": "Arbusto de Cetona",
    "酸液源石虫": "Babosa de Origen Ácida",
    "酸液源石虫·α": "Babosa de Origen Ácida · α",
    "重刺天使": "Ángel de Espina Pesada",
    "重刺天使α": "Ángel de Espina Pesada α",
    "重红柱状菌": "Hongo Columna Rojo Pesado",
    "重黯石": "Piedra Oscura Pesada",
    "金石稻": "Arroz de Piedra Dorada",
    "钉刺天使": "Ángel de Púa",
    "钉刺天使α": "Ángel de Púa α",
    "锁闭储藏箱": "Caja de Almacenamiento Cerrada",
    "锦草": "Hierba Brocado",
    "雾火斧甲兽": "Bestia Hacha de Caparazón de Niebla de Fuego",
    "雾火爪牙": "Esbirro de Niebla de Fuego",
    "雾火牙兽": "Bestia Colmillo de Niebla de Fuego",
    "音像存档": "Archivo de Audio",
    "高阶培养I": "Cultivo Avanzado I",
    "高阶培养II": "Cultivo Avanzado II",
    "高阶培养III": "Cultivo Avanzado III",
    "高阶培养IV": "Cultivo Avanzado IV",
    "高阶培养V": "Cultivo Avanzado V",
    "黯银柑实": "Fruto Cítrico Plata Oscura",
}

TRANS_INDEX = {lang: i for i, lang in enumerate(LANGS)}

for lang in LANGS:
    po = polib.pofile(f'i18n/{lang}/LC_MESSAGES/ok.po')
    added = 0
    
    # Check which items are already in the .po file
    existing_ids = {entry.msgid for entry in po}
    missing_items = [name for name in item_names if name not in existing_ids]
    
    print(f'{lang}: {len(missing_items)} missing items')
    
    for name in missing_items:
        if lang == 'zh_CN':
            translation = name
        elif lang == 'zh_TW':
            translation = SIMPLIFIED_TO_TRADITIONAL.get(name, name)
        elif lang == 'en_US':
            translation = EN_TRANSLATIONS.get(name, name)
        elif lang == 'ja_JP':
            translation = JA_TRANSLATIONS.get(name, name)
        elif lang == 'ko_KR':
            translation = KO_TRANSLATIONS.get(name, name)
        elif lang == 'es_ES':
            translation = ES_TRANSLATIONS.get(name, name)
        else:
            translation = name
        
        entry = polib.POEntry(msgid=name, msgstr=translation)
        po.append(entry)
        added += 1
    
    if added > 0:
        po.save(f'i18n/{lang}/LC_MESSAGES/ok.po')
        print(f'{lang}: added {added} entries')
    else:
        print(f'{lang}: all items already present')

print("\nDone! All .po files updated.")
